public class inal {
	 /* .source "R.java" */
	 /* # annotations */
	 /* .annotation system Ldalvik/annotation/EnclosingClass; */
	 /* value = Lcom/emman/vog/R; */
} // .end annotation
/* .annotation system Ldalvik/annotation/InnerClass; */
/* accessFlags = 0x19 */
/* name = "drawable" */
} // .end annotation
/* # static fields */
public static final Integer americanalligator1;
public static final Integer americanalligator2;
public static final Integer americanbadger1;
public static final Integer americanbadger2;
public static final Integer americanbison1;
public static final Integer americanbison2;
public static final Integer americanblackbear1;
public static final Integer americanblackbear2;
public static final Integer americanmink1;
public static final Integer americanmink2;
public static final Integer americanwigeon1;
public static final Integer americanwigeon2;
public static final Integer back01;
public static final Integer bobcat1;
public static final Integer bobcat2;
public static final Integer browngrizzlybear1;
public static final Integer browngrizzlybear2;
public static final Integer buffalo1;
public static final Integer buffalo2;
public static final Integer collaredpeccary1;
public static final Integer collaredpeccary2;
public static final Integer commonwarthog1;
public static final Integer commonwarthog2;
public static final Integer easterngraysquirrel1;
public static final Integer easterngraysquirrel2;
public static final Integer elephant1;
public static final Integer elephant2;
public static final Integer elk1;
public static final Integer elk2;
public static final Integer empty;
public static final Integer foxsquirrel1;
public static final Integer foxsquirrel2;
public static final Integer graywolf1;
public static final Integer graywolf2;
public static final Integer greaterkudu1;
public static final Integer greaterkudu2;
public static final Integer greathornedowl1;
public static final Integer greathornedowl2;
public static final Integer hippopotamus1;
public static final Integer hippopotamus2;
public static final Integer hyenas1;
public static final Integer hyenas2;
public static final Integer ic_launcher;
public static final Integer leopard1;
public static final Integer leopard2;
public static final Integer life_empty;
public static final Integer life_full;
public static final Integer lion1;
public static final Integer lion2;
public static final Integer lynx1;
public static final Integer lynx2;
public static final Integer mallardduck1;
public static final Integer mallardduck2;
public static final Integer menu_back;
public static final Integer moose1;
public static final Integer moose2;
public static final Integer mountaingoat1;
public static final Integer mountaingoat2;
public static final Integer mountainlion1;
public static final Integer mountainlion2;
public static final Integer muskox1;
public static final Integer muskox2;
public static final Integer northamericanbeaver1;
public static final Integer northamericanbeaver2;
public static final Integer northamericanporcupine1;
public static final Integer northamericanporcupine2;
public static final Integer northernpintail1;
public static final Integer northernpintail2;
public static final Integer nothernriverotter1;
public static final Integer nothernriverotter2;
public static final Integer olivebaboon1;
public static final Integer olivebaboon2;
public static final Integer pheasant1;
public static final Integer pheasant2;
public static final Integer polarbear1;
public static final Integer polarbear2;
public static final Integer quail1;
public static final Integer quail2;
public static final Integer raccoon1;
public static final Integer raccoon2;
public static final Integer redfox1;
public static final Integer redfox2;
public static final Integer redkangaroo1;
public static final Integer redkangaroo2;
public static final Integer right;
public static final Integer right1;
public static final Integer right2;
public static final Integer right_button;
public static final Integer ruffedgrouse1;
public static final Integer ruffedgrouse2;
public static final Integer sikadeer1;
public static final Integer sikadeer2;
public static final Integer speak0;
public static final Integer speak1;
public static final Integer speak2;
public static final Integer speak3;
public static final Integer speak4;
public static final Integer speak5;
public static final Integer speak_button;
public static final Integer speaking_animation;
public static final Integer start_0;
public static final Integer start_1;
public static final Integer stripedskunk1;
public static final Integer stripedskunk2;
public static final Integer title;
public static final Integer whiterhinoceros1;
public static final Integer whiterhinoceros2;
public static final Integer whitetaileddeer1;
public static final Integer whitetaileddeer2;
public static final Integer wildboar1;
public static final Integer wildboar2;
public static final Integer wildturkey1;
public static final Integer wildturkey2;
public static final Integer wolverine1;
public static final Integer wolverine2;
public static final Integer woodduck1;
public static final Integer woodduck2;
public static final Integer wrong;
public static final Integer zebra1;
public static final Integer zebra2;
/* # direct methods */
public inal ( ) {
/* .locals 0 */
/* .prologue */
/* .line 13 */
/* invoke-direct {p0}, Ljava/lang/Object;-><init>()V */
return;
} // .end method
