public abstract class org.anddev.andengine.util.constants.TimeConstants {
	 /* # static fields */
	 public static final Integer DAYSPERMONTH;
	 public static final Integer DAYSPERWEEK;
	 public static final Integer HOURSPERDAY;
	 public static final Long MICROSECONDSPERMILLISECOND;
	 public static final Integer MICROSECONDSPERSECOND;
	 public static final Integer MILLISECONDSPERSECOND;
	 public static final Integer MINUTESPERHOUR;
	 public static final Integer MONTHSPERYEAR;
	 public static final Long NANOSECONDSPERMICROSECOND;
	 public static final Long NANOSECONDSPERMILLISECOND;
	 public static final Long NANOSECONDSPERSECOND;
	 public static final Integer SECONDSPERDAY;
	 public static final Integer SECONDSPERHOUR;
	 public static final Float SECONDSPERMICROSECOND;
	 public static final Float SECONDSPERMILLISECOND;
	 public static final Integer SECONDSPERMINUTE;
	 public static final Integer SECONDSPERMONTH;
	 public static final Float SECONDSPERNANOSECOND;
	 public static final Integer SECONDSPERWEEK;
	 public static final Integer SECONDSPERYEAR;
